### ISSUE TITLE
Global Variable to hold extra info

### ISSUE THREAD

**Issue by postopian** [bgh716/TrainTunnel#3]
We need a global variable(map or array) to hold extra info about each tunnel.
The variable should hold following info about each tunnel
 - reference to paired tunnel(could be nil)
 - temporary train reference or id to hold cargo for train inside tunnel
 - references to auto placed signals(should be removed when we remove the tunnel)

Defined in init.lua as global.Tunnels

**Comment by postopian** [comment]
#### Using table vs array
 - Use table, as we need unique id for tunnels anyways
 - https://www.luascript.dev/blog/creating-maps-using-tables
 - use entrance's entity.unit_number as unique id

**Comment by bgh716** [comment]
#### data refactorying
  - Now every data is in global.Tunnels[mask.unit_number] table
    - Paired tunnels are saved in paired_to key each other
    - train in tunnel is only saved in entrance side (ex. global.Tunnels[mask.unit_number].train)
